### ISSUE TITLE
支持取消中文标点符号的补全

### ISSUE THREAD

**Issue by w1475963** [wlh320/rime-ls#62]
有的时候，我其实不是那么需要中文标点符号的补全。（如图）

![Image](https://github.com/user-attachments/assets/1df3fc14-ab98-4b57-b602-364c03c544b1)

我希望添加一个功能：
在lsp设置里添加一个是否启用中文标点的选项。如果不启用，则不提供中文标点补全。

**Comment by wlh320** [comment]
目前代码里没有对标点符号进行额外判断。

印象中应该可以通过修改 Rime 的配置做到，我找个时间试一下。

如果配置 Rime 能做到的事情，在这里就不重复做了。

**Comment by w1475963** [comment]
```yaml
punctuator:
  digit_separators: ",.:"  
  full_shape:
    ' ' : { commit: '　' }
    ',' : { commit: ， }
    # ...
  half_shape:
    # ',' : '，'
    # '.' : '。'
    # '<' : '《'
    # '>' : '》'
    # '/' : '/'
    # '?' : '？'
    # ...

```
注释掉half_shape后，就没有引号的补全了，不过会有奇怪的点：

![Image](https://github.com/user-attachments/assets/0775a0cd-868c-4587-b90f-870a65dcff45)

我设置了trigger为 `>`(一直)，但似乎这里不需要trigger就能引发。我猜测这可能有前面(和最后）是数字的原因。

![Image](https://github.com/user-attachments/assets/d32bcc82-8366-4a90-9e5f-5c92e5a42da0)

![Image](https://github.com/user-attachments/assets/f8b29bc4-be61-479f-af53-1192c9f61ee4)
